apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
    {{- include "helpdesk.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: BACKEND_URL
              value: http://{{ .Release.Name }}-backend:8000
          readinessProbe:
            httpGet: {path: /, port: http}
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet: {path: /, port: http}
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
    {{- include "helpdesk.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
